repos:
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: master
    hooks:
      - id: luacheck
        args: ["--config", ".luacheckrc"]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
